/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.FernandezSergiPerezMaria.vista;


import edu.ub.prog2.utils.AplicacioException;
import edu.ub.prog2.FernandezSergiPerezMaria.controlador.Controlador;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;


/**
 *
 * @author Sergi
 */
public class AplicacioUB4 extends javax.swing.JFrame {

    Controlador c;
    private int windowWidth = 820;
    private int windowHeight = 610;
    /**
     * Creates new form NewJFrame
     */
    public AplicacioUB4() {
        initComponents();
        c = new Controlador();
        btnNext.setEnabled(false);
        btnPlay.setEnabled(false);
        btnPause.setEnabled(false);
        btnAleatoria.setEnabled(false);
        btnContinua.setEnabled(false);
        btnStop.setEnabled(false);
        this.setResizable(false);
        this.setSize(windowWidth, windowHeight);
        omplirLlistaAlbums();
        omplirLlistaFitxers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comprovadorMenu = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        btnCarregarDades = new javax.swing.JButton();
        btnGuardarDades = new javax.swing.JButton();
        btnGestioBiblioteca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFitxers = new javax.swing.JList<String>();
        btnPlay = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnContinua = new javax.swing.JButton();
        btnAleatoria = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAlbums = new javax.swing.JList<String>();
        btnGestioAlbum = new javax.swing.JButton();
        btnReproduirAlbum = new javax.swing.JButton();
        btnReproduirBiblioteca = new javax.swing.JButton();
        btnReproduirFitxer = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnCrearAlbum = new javax.swing.JButton();
        btnAfegirFitxer = new javax.swing.JButton();
        btnEsborrarFitxer = new javax.swing.JButton();
        btnEsborrarAlbum = new javax.swing.JButton();

        comprovadorMenu.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));
        setPreferredSize(new java.awt.Dimension(805, 610));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnCarregarDades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/LoadButton.png"))); // NOI18N
        btnCarregarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarDadesActionPerformed(evt);
            }
        });

        btnGuardarDades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/SaveButton.png"))); // NOI18N
        btnGuardarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDadesActionPerformed(evt);
            }
        });

        btnGestioBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/BibliotecaButton.png"))); // NOI18N
        btnGestioBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioBibliotecaActionPerformed(evt);
            }
        });

        lstFitxers.setBackground(new java.awt.Color(51, 51, 51));
        lstFitxers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lstFitxers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstFitxers.setForeground(new java.awt.Color(208, 12, 208));
        lstFitxers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstFitxers);

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/PlayButtonInactive.png"))); // NOI18N
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/PauseButtonInactive.png"))); // NOI18N
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/NextButtonInactive.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnContinua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/CiclicButtonInactive.png"))); // NOI18N
        btnContinua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuaActionPerformed(evt);
            }
        });

        btnAleatoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/RandomButtonInactive.png"))); // NOI18N
        btnAleatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatoriaActionPerformed(evt);
            }
        });

        lstAlbums.setBackground(new java.awt.Color(51, 51, 51));
        lstAlbums.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lstAlbums.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstAlbums.setForeground(new java.awt.Color(208, 12, 208));
        lstAlbums.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstAlbums);

        btnGestioAlbum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/AlbumButton.png"))); // NOI18N
        btnGestioAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioAlbumActionPerformed(evt);
            }
        });

        btnReproduirAlbum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/ReproduirAlbumButton.png"))); // NOI18N
        btnReproduirAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproduirAlbumActionPerformed(evt);
            }
        });

        btnReproduirBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/ReproduirBibliotecaButton.png"))); // NOI18N
        btnReproduirBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproduirBibliotecaActionPerformed(evt);
            }
        });

        btnReproduirFitxer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/ReproduirFitxerButton.png"))); // NOI18N
        btnReproduirFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproduirFitxerActionPerformed(evt);
            }
        });

        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/StopButtonInactive.png"))); // NOI18N
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnCrearAlbum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/CrearAlbumButton.png"))); // NOI18N
        btnCrearAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAlbumActionPerformed(evt);
            }
        });

        btnAfegirFitxer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/AfegirFitxerButton.png"))); // NOI18N
        btnAfegirFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirFitxerActionPerformed(evt);
            }
        });

        btnEsborrarFitxer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/EsborrarFitxerButton.png"))); // NOI18N
        btnEsborrarFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsborrarFitxerActionPerformed(evt);
            }
        });

        btnEsborrarAlbum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImatgesProjecte/EsborrarAlbumButton.png"))); // NOI18N
        btnEsborrarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsborrarAlbumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(btnAleatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnContinua, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnGuardarDades, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(btnCarregarDades, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnGestioBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnGestioAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCrearAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEsborrarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnReproduirBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReproduirAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(btnReproduirFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnAfegirFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEsborrarFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReproduirAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReproduirBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReproduirFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarregarDades, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarDades, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(btnGestioBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGestioAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEsborrarFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAfegirFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnContinua, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAleatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEsborrarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsborrarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsborrarAlbumActionPerformed
        if (lstAlbums.getSelectedValue() != null) {
            String nom = lstAlbums.getSelectedValue();
            try {
                c.esborrarAlbum(nom);
            } catch (AplicacioException ex) {
                JOptionPane j = new JOptionPane();
                j.showMessageDialog(this, ex.getMessage(), "Error", j.ERROR_MESSAGE);
            }
        } else {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, "Selecciona l'album que vols esborrar", "Error", j.ERROR_MESSAGE);
        }
        omplirLlistaAlbums();
    }//GEN-LAST:event_btnEsborrarAlbumActionPerformed

    private void btnEsborrarFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsborrarFitxerActionPerformed
        if (lstFitxers.getSelectedIndex() != -1) {
            if (comprovadorMenu.isEnabled()) {
                int esborrar = lstFitxers.getSelectedIndex();
                try {
                    c.esborrarFitxer(esborrar);
                } catch (AplicacioException e) {
                    JOptionPane j = new JOptionPane();
                    j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
                }
            } else {
                int esborrar = lstFitxers.getSelectedIndex();
                String album = lstAlbums.getSelectedValue();
                try {
                    c.esborrarFitxer(album, esborrar);
                } catch (AplicacioException e) {
                    JOptionPane j = new JOptionPane();
                    j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
                }
            }
        }
        else{
            JOptionPane j = new JOptionPane();
                    j.showMessageDialog(this, "Selecciona un fitxer", "Error", j.ERROR_MESSAGE);
        }
        omplirLlistaFitxers();
    }//GEN-LAST:event_btnEsborrarFitxerActionPerformed

    private void btnAfegirFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirFitxerActionPerformed
        if (comprovadorMenu.isEnabled()) {
            JFrame formulari = new FrmAfegirFitxerMultimedia(c, this); 
            formulari.setVisible(true);
           
        } 
        else {
            String album = lstAlbums.getSelectedValue();
            JFrame formulari = new FrmAfegirFitxerAlbum(c, album, this); 
            formulari.setVisible(true);
           
        }
        omplirLlistaFitxers();
    }//GEN-LAST:event_btnAfegirFitxerActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        try {
            c.tancarFinestraReproductor();
        } catch (AplicacioException e) {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
        }
        btnNext.setEnabled(false);
        btnPlay.setEnabled(false);
        btnPause.setEnabled(false);
        btnAleatoria.setEnabled(false);
        btnContinua.setEnabled(false);
        btnStop.setEnabled(false);
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnReproduirFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproduirFitxerActionPerformed
        if (lstFitxers.getSelectedIndex() != -1) {
            int reproduir = lstFitxers.getSelectedIndex();
            System.out.println(reproduir);
            try {
                c.obrirFinestraReproductor();
                c.reproduirFitxer(reproduir);
            } catch (AplicacioException e) {
                JOptionPane j = new JOptionPane();
                j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
            }
            btnNext.setEnabled(true);
            btnPlay.setEnabled(true);
            btnPause.setEnabled(true);
            btnAleatoria.setEnabled(true);
            btnContinua.setEnabled(true);
            btnStop.setEnabled(true);
        } else {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, "No s'ha seleccionat cap fitxer", "Error", j.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReproduirFitxerActionPerformed

    private void btnReproduirBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproduirBibliotecaActionPerformed
        try {
            c.obrirFinestraReproductor();
            c.reproduirCarpeta();
            btnNext.setEnabled(true);
            btnPlay.setEnabled(true);
            btnPause.setEnabled(true);
            btnAleatoria.setEnabled(true);
            btnContinua.setEnabled(true);
            btnStop.setEnabled(true);
        } catch (AplicacioException e) {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
        }
        comprovadorMenu.setEnabled(false);
        omplirLlistaFitxers(); 
    }//GEN-LAST:event_btnReproduirBibliotecaActionPerformed

    private void btnReproduirAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproduirAlbumActionPerformed
        try {
            c.obrirFinestraReproductor();
            c.reproduirCarpeta(lstAlbums.getSelectedValue());
        } catch (AplicacioException e) {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
        }
        btnNext.setEnabled(true);
        btnPlay.setEnabled(true);
        btnPause.setEnabled(true);
        btnAleatoria.setEnabled(true);
        btnContinua.setEnabled(true);
        btnStop.setEnabled(true);
        comprovadorMenu.setEnabled(false);
        omplirLlistaFitxers(); 
    }//GEN-LAST:event_btnReproduirAlbumActionPerformed

    private void btnGestioAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioAlbumActionPerformed
        comprovadorMenu.setEnabled(false);
        if (lstAlbums.getSelectedValue() != null) {
            omplirLlistaFitxers();
        } else {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, "No s'ha seleccionat cap album", "Error", j.ERROR_MESSAGE);
            comprovadorMenu.setEnabled(true); 
        }

    }//GEN-LAST:event_btnGestioAlbumActionPerformed

    private void btnAleatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatoriaActionPerformed
        c.setReproduccioAleatoria();
    }//GEN-LAST:event_btnAleatoriaActionPerformed

    private void btnContinuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuaActionPerformed
        c.setReproduccioCiclica();
    }//GEN-LAST:event_btnContinuaActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            c.saltaReproduccio();
        } catch (AplicacioException e) {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        try {
            c.pausaReproduccio();
        } catch (AplicacioException e) {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        try {
            c.reemprenReproduccio();
        } catch (AplicacioException e) {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnGestioBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioBibliotecaActionPerformed
        //Metode guay
        comprovadorMenu.setEnabled(true);
        omplirLlistaFitxers();
        //Mostrar biblioteca
    }//GEN-LAST:event_btnGestioBibliotecaActionPerformed

    private void btnGuardarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDadesActionPerformed
        try {
            JOptionPane j = new JOptionPane();
            c.guardarDadesDisc("C:\\Users\\sergi\\Desktop\\holasi.dat");
            j.showMessageDialog(this, "S'han guardat les dades", "Guardar Dades", j.INFORMATION_MESSAGE);

        } catch (AplicacioException e) {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarDadesActionPerformed

    private void btnCarregarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarDadesActionPerformed
        try {
            JOptionPane j = new JOptionPane();
            c.carregarDadesDisc("C:\\Users\\sergi\\Desktop\\holasi.dat");
            omplirLlistaAlbums();
            omplirLlistaFitxers();
            j.showMessageDialog(this, "S'han carregat les dades", "Carregar Dades", j.INFORMATION_MESSAGE);

        } catch (AplicacioException e) {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCarregarDadesActionPerformed

    private void btnCrearAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAlbumActionPerformed
        String nom = JOptionPane.showInputDialog(this, "Introdueix el nom del album");
        try {
            c.afegirAlbum(nom);
        } catch (AplicacioException e) {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
        }
        omplirLlistaAlbums();

    }//GEN-LAST:event_btnCrearAlbumActionPerformed
    public void omplirLlistaAlbums() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        for (String item : c.mostrarLlistatAlbums()) {
            model.addElement(item);
        }
        lstAlbums.setModel(model);
    }

    public void omplirLlistaFitxers() {
        try {
            DefaultListModel model = new DefaultListModel();
            model.clear();
            if (comprovadorMenu.isEnabled()) {
                for (String item : c.mostrarBiblioteca()) {
                    model.addElement(item);
                }
                lstFitxers.setModel(model);
            } else if (!comprovadorMenu.isEnabled() && lstAlbums.getSelectedIndex() != -1) {
                for (String item : c.mostrarAlbum(lstAlbums.getSelectedValue())) {
                    model.addElement(item);
                }
                lstFitxers.setModel(model);
            }
        } catch (AplicacioException e) {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicacioUB4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirFitxer;
    private javax.swing.JButton btnAleatoria;
    private javax.swing.JButton btnCarregarDades;
    private javax.swing.JButton btnContinua;
    private javax.swing.JButton btnCrearAlbum;
    private javax.swing.JButton btnEsborrarAlbum;
    private javax.swing.JButton btnEsborrarFitxer;
    private javax.swing.JButton btnGestioAlbum;
    private javax.swing.JButton btnGestioBiblioteca;
    private javax.swing.JButton btnGuardarDades;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnReproduirAlbum;
    private javax.swing.JButton btnReproduirBiblioteca;
    private javax.swing.JButton btnReproduirFitxer;
    private javax.swing.JButton btnStop;
    private javax.swing.JToggleButton comprovadorMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstAlbums;
    private javax.swing.JList<String> lstFitxers;
    // End of variables declaration//GEN-END:variables
}
