/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.FernandezSergiPerezMaria.vista;

import edu.ub.prog2.FernandezSergiPerezMaria.controlador.Controlador;
import edu.ub.prog2.utils.AplicacioException;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergi
 */
public class FrmAfegirFitxerMultimedia extends javax.swing.JFrame {

    Controlador c;
    AplicacioUB4 x;
    private int windowWidth = 480;
        private int windowHeight = 330;

    public FrmAfegirFitxerMultimedia(Controlador c, AplicacioUB4 x) {
        this.c = c;
        initComponents();
        this.x = x;
        this.setResizable(false);
        this.setSize(windowWidth, windowHeight);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCamiVideo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomVideo = new javax.swing.JTextField();
        txtCodecVideo = new javax.swing.JTextField();
        txtCamiAudio = new javax.swing.JTextField();
        txtCodecAudio = new javax.swing.JTextField();
        txtNomAudio = new javax.swing.JTextField();
        txtCamiImatge = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnAfegirVideo = new javax.swing.JButton();
        btnAfegirAudio = new javax.swing.JButton();
        btnCamiAudio = new javax.swing.JButton();
        btnCamiVideo = new javax.swing.JButton();
        btnCamiImatge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        txtCamiVideo.setBackground(new java.awt.Color(51, 51, 51));
        txtCamiVideo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(208, 12, 208));
        jLabel1.setText("Camí");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(208, 12, 208));
        jLabel2.setText("Nom");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(208, 12, 208));
        jLabel3.setText("Codec");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(208, 12, 208));
        jLabel4.setText("Imatge");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(208, 12, 208));
        jLabel5.setText("Codec");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(208, 12, 208));
        jLabel6.setText("Nom");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(208, 12, 208));
        jLabel7.setText("Camí");

        txtNomVideo.setBackground(new java.awt.Color(51, 51, 51));
        txtNomVideo.setForeground(new java.awt.Color(255, 255, 255));

        txtCodecVideo.setBackground(new java.awt.Color(51, 51, 51));
        txtCodecVideo.setForeground(new java.awt.Color(255, 255, 255));

        txtCamiAudio.setBackground(new java.awt.Color(51, 51, 51));
        txtCamiAudio.setForeground(new java.awt.Color(255, 255, 255));

        txtCodecAudio.setBackground(new java.awt.Color(51, 51, 51));
        txtCodecAudio.setForeground(new java.awt.Color(255, 255, 255));

        txtNomAudio.setBackground(new java.awt.Color(51, 51, 51));
        txtNomAudio.setForeground(new java.awt.Color(255, 255, 255));

        txtCamiImatge.setBackground(new java.awt.Color(51, 51, 51));
        txtCamiImatge.setForeground(new java.awt.Color(255, 255, 255));

        btnBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\TornarButton.png")); // NOI18N
        btnBack.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\TornarButton.png")); // NOI18N
        btnBack.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\TornarButtonDragged.png")); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAfegirVideo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\VideoButton.png")); // NOI18N
        btnAfegirVideo.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\VideoButton.png")); // NOI18N
        btnAfegirVideo.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\VideoButtonDragged.png")); // NOI18N
        btnAfegirVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirVideoActionPerformed(evt);
            }
        });

        btnAfegirAudio.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\AudioButton.png")); // NOI18N
        btnAfegirAudio.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\AudioButton.png")); // NOI18N
        btnAfegirAudio.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\AudioButtonDragged.png")); // NOI18N
        btnAfegirAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirAudioActionPerformed(evt);
            }
        });

        btnCamiAudio.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\FitxButton.png")); // NOI18N
        btnCamiAudio.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\FitxButton.png")); // NOI18N
        btnCamiAudio.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\FitxButtonDragged.png")); // NOI18N
        btnCamiAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamiAudioActionPerformed(evt);
            }
        });

        btnCamiVideo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\FitxButton.png")); // NOI18N
        btnCamiVideo.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\FitxButton.png")); // NOI18N
        btnCamiVideo.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\FitxButtonDragged.png")); // NOI18N
        btnCamiVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamiVideoActionPerformed(evt);
            }
        });

        btnCamiImatge.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\FitxButton.png")); // NOI18N
        btnCamiImatge.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\FitxButton.png")); // NOI18N
        btnCamiImatge.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\FitxButtonDragged.png")); // NOI18N
        btnCamiImatge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamiImatgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAfegirVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAfegirAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodecVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCamiVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCamiVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCamiImatge, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodecAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCamiAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCamiAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCamiImatge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCamiVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCamiAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCamiVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCamiAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNomVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodecAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodecVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCamiImatge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtCamiImatge, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAfegirAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAfegirVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCamiAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamiAudioActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        txtCamiAudio.setText(f.getAbsolutePath());
    }//GEN-LAST:event_btnCamiAudioActionPerformed

    private void btnAfegirVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirVideoActionPerformed
        try {
            c.afegirVideo(txtCamiVideo.getText(), txtNomVideo.getText(), txtCodecVideo.getText(), 0, 0, 0, 0);
        } catch (AplicacioException e) {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
        }
        x.omplirLlistaFitxers();
        dispose();
    }//GEN-LAST:event_btnAfegirVideoActionPerformed

    private void btnCamiVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamiVideoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        txtCamiVideo.setText(f.getAbsolutePath());
    }//GEN-LAST:event_btnCamiVideoActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCamiImatgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamiImatgeActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        txtCamiImatge.setText(f.getAbsolutePath());
    }//GEN-LAST:event_btnCamiImatgeActionPerformed

    private void btnAfegirAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirAudioActionPerformed
        try {
            c.afegirAudio(txtCamiAudio.getText(), txtCamiImatge.getText(), txtNomAudio.getText(), txtCodecAudio.getText(), 0, 0);
        } catch (AplicacioException e) {
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
        }
        x.omplirLlistaFitxers();
        dispose();
    }//GEN-LAST:event_btnAfegirAudioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirAudio;
    private javax.swing.JButton btnAfegirVideo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCamiAudio;
    private javax.swing.JButton btnCamiImatge;
    private javax.swing.JButton btnCamiVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCamiAudio;
    private javax.swing.JTextField txtCamiImatge;
    private javax.swing.JTextField txtCamiVideo;
    private javax.swing.JTextField txtCodecAudio;
    private javax.swing.JTextField txtCodecVideo;
    private javax.swing.JTextField txtNomAudio;
    private javax.swing.JTextField txtNomVideo;
    // End of variables declaration//GEN-END:variables
}
