/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.FernandezSergiPerezMaria.vista;

import edu.ub.prog2.FernandezSergiPerezMaria.controlador.Controlador;
import edu.ub.prog2.utils.AplicacioException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergi
 */
public class FrmAfegirFitxerAlbum extends javax.swing.JFrame {

    String nom;
    Controlador c;
    AplicacioUB4 x;

    public FrmAfegirFitxerAlbum(Controlador c, String nom, AplicacioUB4 x) {
        initComponents();
        this.c = c;
        this.nom = nom;
        this.x = x;
        omplirLlistaFitxers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFitxers = new javax.swing.JList<>();
        btnAfegirFitxerAlbum = new javax.swing.JButton();
        btnTornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lstFitxers.setBackground(new java.awt.Color(51, 51, 51));
        lstFitxers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstFitxers.setForeground(new java.awt.Color(208, 12, 208));
        lstFitxers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstFitxers);

        btnAfegirFitxerAlbum.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\AfegirButton.png")); // NOI18N
        btnAfegirFitxerAlbum.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\AfegirButton.png")); // NOI18N
        btnAfegirFitxerAlbum.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\AfegirButtonDragged.png")); // NOI18N
        btnAfegirFitxerAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirFitxerAlbumActionPerformed(evt);
            }
        });

        btnTornar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\TornarButton.png")); // NOI18N
        btnTornar.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\TornarButton.png")); // NOI18N
        btnTornar.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Sergi\\Desktop\\SergiFernandezMariaPerez4\\src\\ImatgesProjecte\\TornarButtonDragged.png")); // NOI18N
        btnTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAfegirFitxerAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnTornar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTornar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAfegirFitxerAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfegirFitxerAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirFitxerAlbumActionPerformed
        if (lstFitxers.getSelectedIndex() != -1) {
            try {
                c.afegirFitxer(nom, lstFitxers.getSelectedIndex());
            } catch (AplicacioException e) {
                JOptionPane j = new JOptionPane();
                j.showMessageDialog(this, e.getMessage(), "Error", j.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane j = new JOptionPane();
            j.showMessageDialog(this, "Selecciona un fitxer", "Error", j.ERROR_MESSAGE);
        }
        x.omplirLlistaFitxers();
        dispose();
    }//GEN-LAST:event_btnAfegirFitxerAlbumActionPerformed

    private void btnTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTornarActionPerformed
        dispose(); 
    }//GEN-LAST:event_btnTornarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void omplirLlistaFitxers() {

        DefaultListModel model = new DefaultListModel();
        model.clear();

        for (String item : c.mostrarBiblioteca()) {
            model.addElement(item);
        }
        lstFitxers.setModel(model);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirFitxerAlbum;
    private javax.swing.JButton btnTornar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstFitxers;
    // End of variables declaration//GEN-END:variables
}
